# Dataset / Model parameters
data_dir: /zhengzeqi/vit_test/ViT_test_experiment/data/tiny_imagenet_200
dataset: tiny_imagenet
pretrained: False
num_classes: 200
num_heads: 8
img_size: 64
mean:
    - 0.485
    - 0.456
    - 0.406
std:
    - 0.229
    - 0.224
    - 0.225
crop_pct: 1.0
scale:
    - 1.0
    - 1.0
ratio: [1.0, 1.0]
interpolation: bicubic
train_interpolation: bicubic
use_conv_as_linear: true
pooling_stat: "0111"
time_steps: 4
layer: 6
dim: 512
mlp_ratio: 4

# Augmentation & regularization parameters
aa: rand-m9-n1-mstd0.4-inc1
color_jitter: 0.5
mixup: 0.5
mixup_off_epoch: 200
mixup_prob: 1.0
mixup_mode: batch
mixup_switch_prob: 0.5
cutmix: 0.0

# Model Exponential Moving Average
model-ema: False
model-ema-decay: 0.9998

# Misc
seed: 42
amp: true
apex_amp: false             # changed on 2025-04-23
channels-last: False
batch_size: 128
val_batch_size: 64
lr: 5e-4
min_lr: 1e-5
sched: cosine
weight_decay: 6e-2
epochs: 200
cooldown_epochs: 10
warmup_epochs: 20
warmup_lr: 1e-6
opt: adamw
smoothing: 0.1
workers: 8


# Additional
# Random erase prob
reprob: 0.25
remode: pixel
recount: 1
